application: tallyhomeapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /index\.html
  script: home.py

- url: /stylesheets
  static_dir: stylesheets

- url: /appstuff
  static_dir: appstuff

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /admin/.*
  script: admin.py
  login: admin

- url: /v1/data
  script: data.py

- url: /avgPrice
  script: data.py

- url: /.*
  script: not_found.py

builtins:
- datastore_admin: on
- remote_api: on
